### ISSUE TITLE
Not really a Issue

### ISSUE THREAD

**Issue by AuroraCrimsonRose** [T-800a/altv-T800a-sandbox#1]
I had a quick question I wondering if you have any of the Scripts you had from armaholic before it died?
I'm looking for the data download script.

**Comment by T-800a** [comment]
Hey, sorry for the late response.
the data download script is contained in the SME.Gen Missions, see:
https://github.com/T-800a/SME.Gen/tree/development/_SMEGen_.Altis/scripts
